<h2 class="time-header">TXJS | Live Captioning</h2>
<iframe class="streamtext" src="https://www.streamtext.net/player?event=TXJS15&amp;ff=Open%20Sans,Helvetica,sans-serif&amp;fs=48&amp;fgc=1c1f51&amp;bgc=transparent&amp;spacing=1.4&amp;header=false&amp;scroll=false&amp;controls=false&amp;footer=false&amp;chat=false&amp;content-style=font-weight:bold;margin:0;" width="100%" height="500" frameborder="0"></iframe>
<h2 class="time-header"></h2>
