<footer id="footer" class="container-fluid">
  <div class="row">
    <div class="col-xs">
      <h2>Thanks to our Sponsors</h2>

      <a href=http://www.bocoup.com/><img src=pixels/sponsors/bocoup-450.png alt="Bocoup" width=95 height=146 /></a>
      <a href=http://roost.bocoup.com/><img src=pixels/sponsors/roost.png?2 alt="Roost JavaScript Training" width=146 height=146 style="padding-top:30px;" /></a>
      <br style="clear:both;padding-top:40px;" />
      <a href=https://www.spredfast.com/about-us/careers/><img src=pixels/sponsors/spredfast-logo-2.svg width=300 style="padding-top:20px;" alt="Spredfast" /></a>
      <br style="clear:both;padding-top:20px;" />
      <a href=http://www.bazaarvoice.com/careers/research-and-development/front-end.html><img src=pixels/sponsors/bv.png style="padding:20px 0;" width=300 alt="Bazaarvoice" /></a>
      <br style="clear:both;padding-top:20px;" />
      <a href=http://www.homeaway.com/search/refined/texas/austin/region:7116/keywords:Austin+TX/Location+Type:downtown/Online+Booking:Book+Online/Payment:Online+Payments/arrival:2015-07-22/departure:2015-07-25/minSleeps/1/maxSleeps/4>
        <img src=pixels/sponsors/homeaway-logo.svg width="300" style="padding-top:2px;" alt="Homeaway" />
      </a>
      <br style="clear:both;padding-top:20px;" />
      <a href="https://ustudio.com/solutions#video-platform-apis-0"><img src="pixels/sponsors/sponsor-ustudio.svg" style="padding:20px 0;" width="300" alt="ustudio" /></a>
      <br style="clear:both;padding-top:20px;" />
      <a href="http://www.retailmenot.com/corp/careers/"><img src="pixels/sponsors/rmn-dark.png" style="padding-top:30px;" width=300 alt="RetailMeNot" /></a>
      <br style="clear:both;padding-top:20px;" />
      <a href="http://www.spiceworks.com/jobs/"><img src="pixels/sponsors/spiceworks-logo.svg" style="padding:45px 0;" width="300" alt="Spiceworks" /></a>
      <br style="clear:both;padding-top:20px;" />
      <a href=https://jquery.org/><img src=pixels/sponsors/logo-jquery-foundation.svg alt="The jQuery Foundation" width=243 height=66 style="margin-top:10px" /></a>

    </div>
  </div>
</footer>
